DIRECTORY_NAME = 'German_topo'
BACKUP_CONF_NUM = 4
SLICE_NODE_NUM = 3
ATTEMPT_NUM = 1
SLICE_NUM_PER_ATTEMPT = 5
NUM_OF_SLICES = ATTEMPT_NUM * SLICE_NUM_PER_ATTEMPT

RESTRICT_WEIGHT = 1000
ISOLATE_WEIGHT = 100000